import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer";
import Script from "next/script";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-muted`}
            >
                <Script
                    src={process.env.NEXT_PUBLIC_MIDTRANS_SNAP_URL}
                    data-client-key={process.env.NEXT_PUBLIC_CLIENT_KEY}
                    strategy="lazyOnload"
                />

                <Toaster position="top-left" reverseOrder={false} />
                {children}
                <Footer />
            </body>
        </html>
    );
}
